name: Update chains_config file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment are you going to update (dev or prod)?'
        required: true
        type: choice
        default: "prod"
        options:
          - dev
          - prod

jobs:
  update-chains-file:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ”§ Install rust dependencies
        uses: ./.github/workflows/rust-install

      - name: ğŸ›  Set up env variables
        uses: ./.github/workflows/setup-env

      - name: ğŸ“ Update chains_config file
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- update-chain-config --env ${{ github.event.inputs.environment }} --version ${{ env.NOVA_CONFIG_VERSION }}

      - name: ğŸ—“ï¸Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: â¡ï¸ Make pull request
        uses: ./.github/workflows/make-pull-request
        with:
          commit-path: config*.toml
          commit-message: Update config file with chains_config
          branch-name: update-chains_config-${{ steps.date.outputs.date }}
          github-token: ${{ secrets.GITHUB_TOKEN }}